matrix.yaml
This PR enables `arm64` AMIs to be created in AWS.
=> Add AWS `arm64` AMIs

.github/workflows/pr.yaml, source.pkr.hcl
This PR updates the root volume size on the AMIs that we create. This is necessary since the default size of 8GB is too small for our bare-metal instances to build QEMU images with.
This change should eventually be removed once we reconfigure the `arc-nv-runtime` to adjust the root device when launching the instance. This will allow us to save $$$ on the EBS snapshots associated with our AMIs.
=> Update root volume size on AMIs 

.dockerignore, .github/workflows/build.yaml, Dockerfile, README.md, ci/clean-up-instance.sh, ci/compute-config-values.sh, ci/compute-image-name.sh, ci/compute-matrix.jq, ci/compute-matrix.sh, ci/setup-qemu-kvm.sh, matrix.yaml, source.pkr.hcl
This PR adds QEMU amd64 builds to create images for KubeVirt.
Packer builds a `qcow2` image, which is then copied into a Docker image according to the KubeVirt instructions here: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk.
The image is then pushed to our ECR registry.
=> Add QEMU amd64 Builds

.github/workflows/build.yaml, .gitignore, README.md, build.pkr.hcl, ci/setup-qemu-kvm.sh, locals.pkr.hcl, matrix.yaml, source.pkr.hcl, variables.auto.pkrvars.hcl.sample, variables.pkr.hcl
This PR enables QEMU builds for `arm64`.
Among other online resources the MAAS example repository below was used as a reference for some of these changes:
- https://github.com/canonical/packer-maas/tree/main/ubuntu
=> Enable `arm64` QEMU builds

matrix.yaml
This PR adds images for drivers `470` and `535`.
Driver `470` is the earliest current LTS branch and `535` is the latest current LTS branch.
source: https://docs.nvidia.com/datacenter/tesla/drivers/index.html#cuda-drivers
=> Add `470` and `535` driver images

scripts/helpers/check_event_type.sh, scripts/helpers/runner.sh, scripts/installers/runner.sh
This PR adds our `check_event_type.sh` script to our VM runners and configures it to run as a pre-start step by setting the `ACTIONS_RUNNER_HOOK_JOB_STARTED` environment variable's value to the path of the script.
=> Add `check_event_type.sh` to runners

.github/workflows/build.yaml, .github/workflows/main.yaml, .github/workflows/pr.yaml, matrix.yaml, renovate.json, scripts/helpers/runner.service, scripts/helpers/runner.sh, source.pkr.hcl, variables.auto.pkrvars.hcl.sample, variables.pkr.hcl
This PR moves the `poweroff` command for our runners to the `systemd` unit file.
It also adds `renovate` to keep the `RUNNER_VERSION` up-to-date.
=> Move `poweroff` to `systemd` unit file & add `renovate`

scripts/helpers/buildkitd.toml, scripts/installers/docker.sh
As for docker, we need to set the docker mirror in the buildkit config file
=> Set docker mirror for buildkit

.github/workflows/build.yaml, .github/workflows/gc.yaml, .github/workflows/pr.yaml, .gitignore, build.pkr.hcl, gc/README.md, gc/collectors/amis.py, gc/collectors/ecr.py, gc/collectors/gc.py, gc/main.py, gc/mypy.ini, gc/requirements.txt, matrix.yaml, scripts/helpers/github.sh, source.pkr.hcl, variables.auto.pkrvars.hcl.sample, variables.pkr.hcl
This PR adds garbage collection scripts for our AMIs and KVM images in ECR.
The script makes the following assumptions:
- any images in the `kubevirt-images` repository that are untagged can be deleted
- any images in the `kubevirt-images` repository whose tags are not in our current matrix can be deleted
- AMIs produced by this repository that are not currently in our matrix can be deleted
- AMIs produced by this repository that are currently in our matrix only need to keep the latest image
As mentioned in the AWS docs below, EBS Snapshots must also be removed after AMIs are deregistered.
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/deregister-ami.html
The script makes use of the following Python packages:
- [`boto3`](https://pypi.org/project/boto3/) - AWS SDK for Python
- …
=> Add Garbage Collection Scripts

matrix.yaml
This PR adds the latest runner application to our images: https://github.com/actions/runner/releases/tag/v2.312.0.
We can test this. Once it's confirmed working, we can remove the previous runner version.
=> Build images for new runner version `2.312.0`

windows/context/verification.ps1, windows/installers/git.ps1
Trying to add `C:\Program Files\Git\bin` to $PATH so the Windows images have bash.exe [like the GitHub hosted runners](https://github.com/actions/runner-images/blob/win22/20240211.1/images/windows/Windows2022-Readme.md#shells).
I don't know powershell, I have no idea if this will work, total shot in the dark.
cc: @wmaxey
=> Add git to PATH in Windows images

matrix.yaml
This runner version can be removed after we upgrade to `2.313.0`.
[skip ci]
=> Remove runner version `2.312.0`

config.yaml
This PR is updating the DNS domain to `local` for he on premise images. Once AWS images are also using the `local` domain, this logic can be removed
=> Use `local` domain for on prem images

matrix.yaml
This PR removes runner version `2.313.0`.
[skip ci]
=> Remove old runner

build.pkr.hcl, linux/context/fluent-bit/aws/aws.conf, linux/context/fluent-bit/common.conf, linux/context/fluent-bit/fluent-bit.conf, linux/context/fluent-bit/qemu/add_node_name.lua, linux/context/fluent-bit/qemu/qemu.conf, linux/installers/fluent-bit.sh
This PR is adding `fluent-bit` to our runners
Each runner is pushing logs to an other `fluent-bit` instance running in each environment (`aws` and `qemu`)
We conditionally include a configuration directory for each environment:
- On `aws`, we use the `aws` filter to include metadata about the EC2 instance
- On `qemu`, we use a Lua script to include the node name in each log
=> Add fluent-bit

linux/context/fluent-bit/aws/aws.conf
We add the EC2 `Name` tag in the logs and then rename it to `runner_name`. This will be used as the log key in CloudWatch
=> Add EC2 Name tag to fluent-bit logs and rename it to runner_name

linux/context/dockerd.gpu.json, linux/context/fluent-bit/common.conf, linux/context/fluent-bit/fluent-bit.conf
- To workaround an issue we are facing with GPU containers and systemd cgroups, we disable systemd cgroups in docker until we can fix the issue
- We remove the systemd filtering we have on fluent-bit logs so we can debug any issue related to any systemd service (like cloud-init)
- We reduce fluent-bit logs that are not really useful by setting the log level to warn
=> Disable systemd cgroups and improve fluent-bit logging

linux/context/dockerd.json, linux/installers/nvidia-container-toolkit.sh
There is a bug in `nvcr` that is not creating `libcuda.so` symlink while using CDI mode. Until `nvcr` is fixed, we need to disable CDI. To prevent issues with `systemd daemon-reload`, we need to disable systemd cgroups
=> Disable CDI and disable systemd cgroups

linux/installers/docker.sh
As we are running in Kubernetes with Calico, we need to adapt the MTU of the containers to `1480`
=> Set MTU for docker in qemu env

matrix.yaml
This PR adds runner version `2.315.0` to our matrix.
=> Add runner version `2.315.0`

linux/installers/apt.sh
`unattended-upgrades` must be disabled to prevent it from upgrading a critical package like the NVIDIA driver
=> Disable unattended-upgrades

matrix.yaml
This PR adds runner version `2.316.1` to our matrix
=> Add runner version `2.316.1`

matrix.yaml
This PR removes the `2.315.0` runner version from our matrix.
=> Remove runner version `2.315.0`

linux/context/runner.service
This PR moves the `{Failure,Success}Action` directives from the `Service` section to the `Unit` section.
As per the docs below, they should be placed in the `Unit` section:
- https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html
=> Move directives in runner unit file

matrix.yaml
This PR adds runner version `2.317.0` to our matrix.
=> Add runner version `2.317.0`

matrix.yaml
This PR removes runner version `2.316.1` since it is no longer in use.
[skip ci]
=> Remove runner version `2.316.1`

linux/context/runner.sh
To ensure the instances are stopped when the runner script is exiting, this PR is adding a trap to run `sudo poweroff -ff` on exit in the runner script
=> Setup trap to poweroff instance in runner script

source.pkr.hcl
Lately, our Windows images in AWS have been throwing a `ResourceNotReady` error:
- https://github.com/nv-gha-runners/vm-images/actions/runs/9697044936/job/26775090346#step:7:262
- https://github.com/nv-gha-runners/vm-images/actions/runs/9697044936/job/26760297797#step:7:261
The link in the logs, https://developer.hashicorp.com/packer/integrations/hashicorp/amazon#resourcenotready-error, suggests that increasing the `aws_polling` values can resolve this.
Therefore, this PR increases the values of the `aws_polling` properties.
The default values are:
```hcl
aws_polling {
delay_seconds = 15
max_attempts = 40
}
```
=> Increase `aws_polling` values

.github/workflows/build.yaml, ci/compute-constants.sh, ci/compute-image-name.sh, ci/compute-matrix.sh, ci/compute-variables.sh, gc/collectors/amis.py, gc/collectors/ecr.py, gc/collectors/gc.py, gc/main.py, gc/requirements.txt, regions.yaml, source.pkr.hcl, variables.pkr.hcl
This PR adds support for copying our AMIs to additional AWS regions.
The additional regions are defined in the new `regions.yaml` file.
The contents of `regions.yaml` are used in the following areas:
- in our `packer` configuration files (passed in as variables)
- in our garbage collection scripts
=> Add support for copying AMIs to multiple regions

source.pkr.hcl
The latest changes in #68 were not enough to prevent Windows AMI build errors. The logs below show the issue happening again:
- https://github.com/nv-gha-runners/vm-images/actions/runs/9893897275/job/27330166398#step:7:266
To prevent the issue from occurring again, I've increased the values further.
These changes should cause `packer` to wait 90 minutes for the Windows AMI to be ready. This should (hopefully) be more than enough time.
Skipping CI since these changes don't affect the images themselves.
[skip ci]
=> Increase `aws_polling` values again

linux/installers/apt.sh
To prevent any update while the runner is running, we should disable snap auto refresh feature
=> Disable snap auto refresh

matrix.yaml
This PR adds runner version `2.319.1` to our matrix.
=> Add runner version `2.319.1`

matrix.yaml
This PR is doing the following:
- Dropping not used driver 535
- Prevent fake GPU images for Windows with driver 550
- Add driver 560 to debug some kernel panic issues
=> Update driver entries

ci/compute-image-name.sh, linux/installers/nvidia-driver.sh, matrix.yaml, variables.pkr.hcl
This PR is switching from using apt packages to runfiles to install the NVIDIA driver. This will help us to better control the driver version we want to install in our images. It's also updating the driver versions by removing EOL driver 470 and adding back driver 535
=> Use runfile to install NVIDIA driver and update driver versions

linux/context/initialize_runner.sh, linux/installers/docker.sh, linux/installers/nvidia-container-toolkit.sh
Reset GPU in runner startup script if there is a GPU available. This should prevent issues if a previous job left the GPU in a bad state. This PR is also fixing a docker permission issue
=> Reset GPU in runner startup script

locals.pkr.hcl
Only use major driver version in tags for GPU amis
=> Fix AMI tags for GPU images

linux/installers/apt.sh
As we are using a `runfile` to install the NVIDIA driver, we must ensure we don't upgrade the driver, otherwise the driver will be built/installed for the previous kernel version and will not be loaded when the VM is started
Example of failures: https://github.com/nv-gha-runners/runner-testing/actions/runs/10993397154/job/30519963334#step:2:5
Kernel upgrade: https://github.com/nv-gha-runners/vm-images/actions/runs/10924064302/job/30325032095#step:8:131
Runfile building for the wrong kernel version: https://github.com/nv-gha-runners/vm-images/actions/runs/10924064302/job/30325032095#step:8:656
=> Prevent kernel upgrades when upgrading all packages

linux/installers/nvidia-driver.sh
Grace Hopper nodes require to use open kernel modules
=> Use open kernel modules for Nvidia driver

linux/context/nvidia-persistenced-override.conf, linux/installers/nvidia-driver.sh
To prevent some GSP timeouts, we need to enable persistence mode on GPUs
=> Enable persistence mode for GPUs

.github/workflows/build.yaml, build.pkr.hcl, ci/compute-image-name.sh, linux/installers/nvidia-driver.sh, locals.pkr.hcl, matrix.yaml, variables.auto.pkrvars.hcl.sample, variables.pkr.hcl
To support all types of GPUs in our runners, we need to publish images for both `legacy` and `open` driver version. This PR is adding a new variable `DRIVER_FLAVOR` to support this
=> Publish legacy and open driver flavors images

build.pkr.hcl, linux/installers/watchdog.sh
This PR is installing and configuring a watchdog daemon. This daemon is in charge to send a heartbeat on the watchdog device to notify that the VM is still alive. This only applies to amd64 and qemu images
=> Install and configure watchdog on amd64 images

gc/collectors/amis.py
Remove a stray `break` that was causing AMIs to not be GC'd.
=> Fix logic error with AMI GC

linux/context/fluent-bit/aws/aws.conf, linux/context/fluent-bit/common.conf, linux/context/fluent-bit/qemu/qemu.conf
This PR updates the Fluent Bit configuration for the VMs.
The goal of these changes is to allow the Fluent Bit aggregator to distinguish between log records and @msarahan's new trace records. Grouping all of the existing records under the `log` tag ensures that the aggregator only sends records matching this tag to CloudWatch.
Currently, there doesn't seem to be a need to tag records more granuarly than `logs` vs. `traces`. However, if the need arises in the future, we can always use Fluent Bit's wildcard or regex matching features, described here https://docs.fluentbit.io/manual/concepts/data-pipeline/router, with tags like `logs.cpu`, `logs.mem`, `logs.systemd`, etc. Corresponding matches can be made with `logs.*`, `logs.(cpu|mem)`, etc.
=> Update Fluent Bit configs

linux/context/fluent-bit/common.conf, matrix.yaml
This PR is updating the Fluent Bit hostname from `logs.local` to `fb.local`.
This PR is also dropping driver `550` images to reduce the build matrix. This version is not used anymore.
=> Update Fluent Bit hostname to `fb.local`

.github/workflows/main.yaml
This trigger was removed in https://github.com/nv-gha-runners/vm-images/pull/104
[skip ci]
=> Add back the trigger to publish images if branch starts with test-

.github/workflows/build.yaml, matrix.yaml, renovate.json
Since the runner version is no longer a matrix value, this PR moves it outside of the `matrix.yaml` file.
=> Move runner version outside of `matrix.yaml`

linux/context/vector/common.yaml
This PR is updating the vector configuration to only collect required metrics
=> vector: only collect required metrics

linux/context/vector/dcgm-exporter.service
This PR is fixing some issues with the DCGM exporter deployment:
- Use dockerhub image instead of nvcr.io: This will ensure we use our docker pull through cache and don't hit any rate limit
- Use `hostname -f` instead of `%H` to get the hostname: Unfortunately, the `%H` variable provided by systemd is checking the hostname when systemd is started, which is not a valid hostname until some services are started. To get the right hostname, we need to use the `hostname` command. This requires to run a sub shell, and so to run our docker command using a shell
=> Fix DCGM exporter

linux/context/vector/qemu-cpu.yaml, linux/context/vector/qemu-gpu.yaml, linux/installers/fluent-bit.sh, linux/installers/vector.sh
This PR is configuring `vector` to collect `systemd` logs and send them to `fluent-bit` on `qemu` images. In addition, this PR is removing the installation of `fluent-bit` on `qemu` images
=> Use vector instead of fluent-bit to collect logs on qemu images

linux/context/vector/qemu-cpu.yaml, linux/context/vector/qemu-gpu.yaml
This PR is updating the Vector config to stop sending logs to Fluent Bit and instead send them to the Vector aggregator
=> vector: push logs to vector aggregator instead of fluent-bit for qemu env

.github/workflows/build.yaml, .github/workflows/pr.yaml, .pre-commit-config.yaml, .yamllint.yaml, gc/collectors/amis.py, gc/collectors/ecr.py, gc/collectors/gc.py, gc/collectors/image_name.py, gc/main.py, gc/requirements.txt, linux/installers/docker.sh, linux/installers/python.sh, pyproject.toml, windows/context/envvars.ps1
I was looking through this repo and noticed that it contains some non-trivial Python code that isn't currently covered by any static analysis.
This PR proposes adding configuration to run the following linters via `pre-commit`:
* `codespell` = catches English typos
* `ruff` = auto-formatting and linting for Python code
* `shellcheck` = linting for shell scripts (this repo already had that running, this just switches it to `pre-commit`)
* various built-in `pre-commit` hooks, like those for fixing files that don't end in a newline
Hopefully these changes will give us a bit more release confidence in changes that touch the various scripts in this repo.
=> [ci] add linting with pre-commit

.github/workflows/gc.yaml
In #124, because of other unrelated CI and my own lack of carefulness, I missed that `black` is run as part of the "garbage collection" workflow, and that that check was failing.
#124 introduced `ruff-format` which does the same thing as `black`. This proposes removing uses of `black` (as RAPIDS is planning to: https://github.com/rapidsai/build-planning/issues/130).
I'll merge this with `[skip ci]` to avoid a build of new images, similar to #124.
=> [ci] remove black from gc workflow
